/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GeorgiaPecansRouteImport } from './routes/georgia-pecans'
import { Route as HoneyRouteImport } from './routes/honey'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TrueCostRouteImport } from './routes/true-cost'
import { Route as VeteransRouteImport } from './routes/veterans'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GeorgiaPecansRoute = GeorgiaPecansRouteImport.update({
  id: '/georgia-pecans',
  path: '/georgia-pecans',
  getParentRoute: () => rootRouteImport,
} as any)
const HoneyRoute = HoneyRouteImport.update({
  id: '/honey',
  path: '/honey',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TrueCostRoute = TrueCostRouteImport.update({
  id: '/true-cost',
  path: '/true-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const VeteransRoute = VeteransRouteImport.update({
  id: '/veterans',
  path: '/veterans',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/georgia-pecans': typeof GeorgiaPecansRoute
  '/honey': typeof HoneyRoute
  '/our-story': typeof OurStoryRoute
  '/shop': typeof ShopRouteWithChildren
  '/true-cost': typeof TrueCostRoute
  '/veterans': typeof VeteransRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/georgia-pecans': typeof GeorgiaPecansRoute
  '/honey': typeof HoneyRoute
  '/our-story': typeof OurStoryRoute
  '/true-cost': typeof TrueCostRoute
  '/veterans': typeof VeteransRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/georgia-pecans': typeof GeorgiaPecansRoute
  '/honey': typeof HoneyRoute
  '/our-story': typeof OurStoryRoute
  '/shop': typeof ShopRouteWithChildren
  '/true-cost': typeof TrueCostRoute
  '/veterans': typeof VeteransRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/georgia-pecans'
    | '/honey'
    | '/our-story'
    | '/shop'
    | '/true-cost'
    | '/veterans'
    | '/shop/$slug'
    | '/shop/'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/georgia-pecans'
    | '/honey'
    | '/our-story'
    | '/true-cost'
    | '/veterans'
    | '/shop/$slug'
    | '/shop'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/georgia-pecans'
    | '/honey'
    | '/our-story'
    | '/shop'
    | '/true-cost'
    | '/veterans'
    | '/shop/$slug'
    | '/shop/'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  GeorgiaPecansRoute: typeof GeorgiaPecansRoute
  HoneyRoute: typeof HoneyRoute
  OurStoryRoute: typeof OurStoryRoute
  ShopRoute: typeof ShopRouteWithChildren
  TrueCostRoute: typeof TrueCostRoute
  VeteransRoute: typeof VeteransRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/georgia-pecans': {
      id: '/georgia-pecans'
      path: '/georgia-pecans'
      fullPath: '/georgia-pecans'
      preLoaderRoute: typeof GeorgiaPecansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honey': {
      id: '/honey'
      path: '/honey'
      fullPath: '/honey'
      preLoaderRoute: typeof HoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/true-cost': {
      id: '/true-cost'
      path: '/true-cost'
      fullPath: '/true-cost'
      preLoaderRoute: typeof TrueCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veterans': {
      id: '/veterans'
      path: '/veterans'
      fullPath: '/veterans'
      preLoaderRoute: typeof VeteransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  GeorgiaPecansRoute: GeorgiaPecansRoute,
  HoneyRoute: HoneyRoute,
  OurStoryRoute: OurStoryRoute,
  ShopRoute: ShopRouteWithChildren,
  TrueCostRoute: TrueCostRoute,
  VeteransRoute: VeteransRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
